steps:
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: 'bash'
  args:
    - '-c'
    - |-
      # Get the MIG name
      MIG_NAME=$1

      # Get the startup script from GitHub
      STARTUP_SCRIPT=$(curl -sSL https://raw.githubusercontent.com/${GITHUB_REPOSITORY}/${GITHUB_BRANCH}/${GITHUB_SHA}/startup.sh)

      # Update the MIG startup script
      gcloud compute instance-groups managed set-startup-script ${MIG_NAME} --startup-script="${STARTUP_SCRIPT}"
options:
  logging: CLOUD_LOGGING_ONLY